//
// Created by lukemartinlogan on 2/3/24.
//

#ifndef HERMES_SHM_INCLUDE_HERMES_SHM_UTIL_COMPRESS_COMPRESS_FACTORY_H_
#define HERMES_SHM_INCLUDE_HERMES_SHM_UTIL_COMPRESS_COMPRESS_FACTORY_H_

#include "bzip2.h"
#include "lzo.h"
#include "zstd.h"

#endif //HERMES_SHM_INCLUDE_HERMES_SHM_UTIL_COMPRESS_COMPRESS_FACTORY_H_
