//
// Created by llogan on 16/11/24.
//

#ifndef HERMES_SHM_INCLUDE_HERMES_SHM_CONSTANTS_SETTINGS_H_
#define HERMES_SHM_INCLUDE_HERMES_SHM_CONSTANTS_SETTINGS_H_

#endif  // HERMES_SHM_INCLUDE_HERMES_SHM_CONSTANTS_SETTINGS_H_
